name: crawler docker compose

on: 
  pull_request:
    branches:
    - master
  schedule: 
  - cron: '0 5 * * 1,4'

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Start containers
      run: docker-compose -f "./crawler/docker-compose.yml" up -d --build
      
    - name: Stop containers
      if: always()
      run: docker-compose down
