name: crawler test and upload issue

on: 
  schedule: 
  - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/workflows/crawler/requirements.txt

    - name: Run main.py
      run: |
        python ./.github/workflows/crawler/main.py
      env: 
        CORONAKAKAOBOT_GITHUB_TOKEN: ${{ secrets.CORONAKAKAOBOT_GITHUB_TOKEN }}
        DAILY_CRAWLER_SERVICE_KEY: ${{ secrets.DAILY_CRAWLER_SERVICE_KEY }}






